server:
  port: 8083

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          username: Istiyakmi9
          password: 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
          uri: https://github.com/Istiyakmi9/ems_config-service
          clone-on-start: true


eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka