server:
  port: 8083

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          username: Istiyakmi9
          password: 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
          uri: https://github.com/Istiyakmi9/bt_vault_key_configuration
          clone-on-start: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
