server:
  port: 8083

spring:
  application:
    name: configserver-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Istiyakmi9/ems_config-service
          clone-on-start: true


eureka:
  client:
    enabled: false

#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka